# SERVER MESSAGES

SERVER_MOVE = "102 MOVE\a\b"
SERVER_TURN_LEFT = "103 TURN LEFT\a\b"
SERVER_TURN_RIGHT = "104 TURN RIGHT\a\b"
SERVER_PICK_UP = "105 GET MESSAGE\a\b"
SERVER_LOGOUT = "106 LOGOUT\a\b"
SERVER_KEY_REQUEST = "107 KEY REQUEST\a\b"
SERVER_OK = "200 OK\a\b"
SERVER_LOGIN_FAILED = "300 LOGIN FAILED\a\b"
SERVER_SYNTAX_ERROR = "301 SYNTAX ERROR\a\b"
SERVER_LOGIC_ERROR = "302 LOGIC ERROR\a\b"
SERVER_KEY_OUT_OF_RANGE_ERROR = "303 KEY OUT OF RANGE\a\b"

CLIENT_RECHARGING = "RECHARGING\a\b"
CLIENT_FULL_POWER = "FULL POWER\a\b"



# TIME CONSTANTS
TIMEOUT = 1
TIMEOUT_RECHARGING = 5

#MAX_LENGTH
USERNAME_MAX_LEN = 18
KEY_MAX_LEN = 3
CONFIRMATION_MAX_LEN = 5
CLIENT_OK_MAX_LEN = 10
CLIENT_RECHARGING_MAX_LEN = 10
CLIENT_FULL_POWER_MAX_LEN = 10
CLIENT_MESSAGE_MAX_LEN = 98