# SERVER MESSAGES

#SERVER_CONFIRMATION = "" # ???

SERVER_MOVE = "102 MOVE\a\b"
SERVER_TURN_LEFT = "103 TURN LEFT\a\b"
SERVER_TURN_RIGHT = "104 TURN RIGHT\a\b"
SERVER_PICK_UP = "105 GET MESSAGE\a\b"
SERVER_LOGOUT = "106 LOGOUT\a\b"
SERVER_KEY_REQUEST = "107 KEY REQUEST\a\b"
SERVER_OK = "200 OK\a\b"
SERVER_LOGIN_FAILED = "300 LOGIN FAILED\a\b"
SERVER_SYNTAX_ERROR = "301 SYNTAX ERROR\a\b"
SERVER_LOGIC_ERROR = "302 LOGIC ERROR\a\b"
SERVER_KEY_OUT_OF_RANGE_ERROR = "303 KEY OUT OF RANGE\a\b"


# CLIENT MESSAGES

#CLIENT_USERNAME = "" # ???
#CLIENT_KEY_ID = ""
#CLIENT_CONFIRMATION
#CLIENT_OK
CLIENT_RECHARGING = "RECHARGING\a\b"
CLIENT_FULL_POWER = "FULL POWER\a\b"
#CLIENT_MESSAGE



# TIME CONSTANTS

TIMEOUT = 1
TIMEOUT_RECHARGING = 5

